[tool.poetry]
name = "referrers"
version = "0.5.0"
description = "Finds the graph of referrers for a Python object"
authors = ["Neil Ferguson"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
networkx = ">=3.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
